def menu():
    print()
    print("Program Perhitungan Luas")
    print("------------------------")
    print()
    print("Pilih Bentuk 2D : ")
    print("1. Persegi Panjang")
    print("2. Lingkaran")
    print("3. Segitiga")
    print("4. Keluar")